name: fruits
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.2.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^2.0.0
  smooth_page_indicator: ^1.1.0
  svg_flutter: any
  test: ^1.25.2
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  flutter_paypal_payment: ^1.0.8
  uuid: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/vuesax/bold/
    - assets/images/vuesax/outline/
  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/constants
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
