name: fruits
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  svg_flutter: any
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/constants
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
